Add bookings
Anthony-Elvek/java-shareit pull request #2
Opened 2023-06-06 12:48 UTC by Anthony-Elvek

2023-06-07 12:05 UTC, NikolaiDem requested changes

2023-06-07 12:05 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank(message = "Items name cant be empty")
Аннотации валидации в модели не нужны.
Аналогично далее и в других моделях)

2023-06-07 14:52 UTC, Anthony-Elvek commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        }
Но по ТЗ еще нет задачи на реализацию ItemRequest где я так понял эта логика которую вы просите

2023-06-07 23:49 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
Не исправлено в CommentRepository

2023-06-07 23:51 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank(message = "Items name cant be empty")
Не исправлено в User

2023-06-07 23:51 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
Не исправлено

2023-06-08 00:07 UTC, NikolaiDem requested changes

2023-06-08 00:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        allLastBookingList = bookingRepository.findFirstByItem_IdInAndItem_Owner_IdAndStartIsBefore(
Лучше list сразу преобразовать в мапу, где ключ - itemId, а значение - список его бронирований, чтобы избавиться от квадратичной зависимости в 131-144 строках.
Аналогично для allNextBookingList

2023-06-08 00:07 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .filter(comment -> Objects.equals(comment.getAuthor().getId(), itemId) && itemId != null)
itemId != null для чего здесь? Первое условие уже учитывает его)

2023-06-09 04:37 UTC, NikolaiDem requested changes

2023-06-09 04:37 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        allItemsList.forEach(itemId -> lastBooking.put(itemId, bookingRepository.findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
Здесь N+1 query issue снова вернулась.
Можно сделать, например, так
        Map<Long, List<Booking>> lastBookingsByItemId = bookingRepository.findFirstByItem_IdInAndItem_Owner_IdAndStartIsBefore(
                        allItemsList,
                        user.getId(),
                        realTimeNow,
                        SORT_DESC).stream()
                .collect(Collectors.groupingBy(booking -> booking.getItem().getId()));
               
Аналогично для next booking и comments

2023-06-09 11:03 UTC, Anthony-Elvek commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        allItemsList.forEach(itemId -> lastBooking.put(itemId, bookingRepository.findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
Почему то постоянно выходит NullPointerException, все перепробовал но не выходит 

return itemList.stream()
                .map(item -> ItemMapper.toResponseItemDto(
                        item,
                        lastBooking.get(item.getId()).stream().findFirst().orElse(null),
                        nextBooking.get(item.getId()).stream().findFirst().orElse(null),
                        comments.get(item.getId()).stream()
                                .map(CommentMapper::toCommentDto)
                                .collect(Collectors.toList())))
                .collect(Collectors.toList());
    }

можете подсказать в чем ошибка?

2023-06-09 15:59 UTC, NikolaiDem requested changes

2023-06-09 15:59 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        allItemsList.forEach(itemId -> lastBooking.put(itemId, bookingRepository.findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
Возможно, lastBooking.get(item.getId()) - это null
Тогда можно lastBooking.getOrDeafult(item.getId(), Collections.emptyList())....

2023-06-09 16:24 UTC, NikolaiDem approved these changes

2023-06-10 14:27 UTC, merged